#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution eva_100.py opt

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 100
tc 1
tc 2
tc 3

for i in {01..20}; do
tc GA-$i random_generator 1 100 1 100 1 100 1 100
done;
for i in {01..04}; do
tc GA-zero-d-$i random_generator 0 0 1 100 1 100 1 100
done;
for i in {01..04}; do
tc GA-zero-a-$i random_generator 1 100 0 0 1 100 1 100
done;
for i in {01..04}; do
tc GA-zero-b-$i random_generator 1 100 1 100 0 0 1 100
done;
for i in {01..04}; do
tc GA-zero-h-$i random_generator 1 100 1 100 1 100 0 0
done;
for i in {01..04}; do
tc GA-zero-da-$i random_generator 0 0 0 0 1 100 1 100
done;
for i in {01..04}; do
tc GA-zero-db-$i random_generator 0 0 1 100 0 0 1 100
done;
for i in {01..04}; do
tc GA-zero-dh-$i random_generator 0 0 1 100 1 100 0 0
done;
for i in {01..04}; do
tc GA-zero-ab-$i random_generator 1 100 0 0 0 0 1 100
done;
for i in {01..04}; do
tc GA-zero-ah-$i random_generator 1 100 0 0 1 100 0 0
done;
for i in {01..04}; do
tc GA-zero-bh-$i random_generator 1 100 1 100 0 0 0 0
done;
for i in {01..04}; do
tc GA-zero-dab-$i random_generator 0 0 0 0 0 0 1 100
done;
for i in {01..04}; do
tc GA-zero-dah-$i random_generator 0 0 0 0 1 100 0 0
done;
for i in {01..04}; do
tc GA-zero-dbh-$i random_generator 0 0 1 100 0 0 0 0
done;
for i in {01..04}; do
tc GA-zero-abh-$i random_generator 1 100 0 0 0 0 0 0
done;
tc GA-zero-dabh random_generator 0 0 0 0 0 0 0 0

tc GA-zero-digit-fail random_generator 2 2 0 0 1 1 6 6
tc GA-zero-digit-fail-2 random_generator 2 2 1 1 1 1 3 3
tc GA-one-digit-fail random_generator 3 3 0 0 1 1 14 14
tc GA-one-digit-fail-2 random_generator 3 3 5 5 9 9 1 1
tc GA-two-digit-fail random_generator 10 10 57 57 100 100 1 1
tc GA-two-digit-fail-2 random_generator 10 10 70 70 80 80 1 1
tc GA-three-digit-fail random_generator 19 19 4 4 3 3 81 81
tc GA-three-digit-fail-2 random_generator 42 42 63 63 99 99 17 17
tc GA-four-digit-fail random_generator 77 77 39 39 100 100 67 67
tc GA-four-digit-fail-2 random_generator 50 50 1 1 50 50 77 77
tc GA-five-digit-fail random_generator 85 85 17 17 100 100 97 97
tc GA-five-digit-fail-2 random_generator 85 85 92 92 25 25 97 97
