#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution atli_100.cpp opt

compile random_generator.py

samplegroup
sample 1
sample 2

group gA 50
for i in {01..10}; do
tc gA-rand-$i random_generator 200 200 0
done;
for i in {11..20}; do
tc gA-rand-$i random_generator 200 200**2 0
done;
tc gA-loop random_generator 200 200**2 1

group gB 50
include_group gA
for i in {01..05}; do
tc gB-rand-$i random_generator 10**5 10**5 0
done;
for i in {06..10}; do
tc gB-rand-$i random_generator 10**3 10**5 0
done;

tc gB-loop random_generator 10**3 10**5 1
