#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution hannes_100.py

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 20
tc 1
tc 2
tc 3

group GB 80
include_group GA
for i in {01..10}; do
tc GB-$i random_generator 3 999
done
tc GB-11 random_generator 1000 1000
