#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution elvar_100.py

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group gA 50
for i in {01..10}; do
tc GA-$i random_generator 1
done;

group gB 50
include_group gA
for i in {01..10}; do
tc GB-$i random_generator 2
done;
for i in {11..20}; do
tc GB-$i random_generator 3
done;

