#!/usr/bin/env bash
export PPATH
PPATH=$(realpath ..)
# shellcheck source-path=SCRIPTDIR
. ../../../testdata_tools/gen.sh

use_solution einar_100.sh

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 100
tc 1
tc 2
tc 3

for i in {04..60}; do
    tc "GA-$i" random_generator 1 100
    desc "Random case."
done;
