#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution atli_100.py

compile random_generator.py
compile exact_generator.py

samplegroup
limits max_n=8
sample 1
sample 2
sample 3

group GA 20
limits max_n=2
for i in {01..25}; do
tc GA-$i random_generator 2
done;
tc 3
tc GA-onlyzero exact_generator 1 0 0
tc GA-onlyones exact_generator 1 1 1
tc GA-onezero-1 exact_generator 2 2 2 0 5
tc GA-onezero-2 exact_generator 2 2 2 1 0
tc GA-onezero-3 exact_generator 2 1000 1 0 5
tc GA-onezero-4 exact_generator 2 1 1000 0 5
tc GA-onezero-5 exact_generator 2 1 0 1000 1
tc GA-onezero-6 exact_generator 2 1 0 1 1000
tc GA-twozeroes exact_generator 2 1 0 0 5
tc GA-ratio exact_generator 2 2 2 4 4
tc GA-nonratio exact_generator 2 1 3 4 5

group GB 20
limits max_n=8
include_group GA
tc 1
tc 2
for i in {01..20}; do
tc GB-$i random_generator 8
done;

group GC 20
limits max_n=50
include_group GB
for i in {01..20}; do
tc GC-$i random_generator 50
done;

group GD 20
limits max_n=500
include_group GC
for i in {01..10}; do
tc GD-$i random_generator 500
done;

group GE 20
limits max_n=100000
include_group GD
for i in {01..05}; do
tc GE-$i random_generator 100000
done;
