#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_100.py

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 100
tc 1
tc 2
tc 3
tc GA-lex-01 random_generator lex
for i in {01..30}; do
tc GA-close-$i random_generator close
done;
for i in {01..30}; do
tc GA-random-$i random_generator random
done;
