#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution drekastelpa2000_100.java

compile random_generator.py
compile same_generator.py
compile zero_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 100
tc 1
tc 2
tc 3

for i in {01..30}; do
    tc GA-$i random_generator 0 10000
done;

for i in {31..60}; do
    tc GA-$i zero_generator 0 10000
done;

for i in {61..90}; do
    tc GA-$i same_generator 0 10000
done;

