#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_100.cpp opt

compile random_generator.py

samplegroup
sample 1
sample 2

group GA 100
tc 1
tc 2
for c in {a..z}; do
    tc GA-$c-1 random_generator 1 1 $c
    tc GA-$c-2 random_generator 2 10 $c
    tc GA-$c-3 random_generator 11 20 $c
done
