#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_100.java

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 100
tc 1
tc 2
tc 3
for i in {01..10}; do
tc GA-$i random_generator 3 1336
done;
for i in {11..30}; do
tc GA-$i random_generator 1338 10**9
done;
