#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_100.py

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 25
for i in {01..20}; do
tc GA-$i random_generator 1 1 always_start_upper
done;

group GB 35
include_group GA
for i in {01..20}; do
tc GB-$i random_generator 2 100 always_start_upper
done;

group GC 40
include_group GB
for i in {01..20}; do
tc GC-$i random_generator 2 100 any_start
done;
