#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_strategic_100.py

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 15
for i in 01 02 03 05 06; do
tc GA-$i random_generator perm 2 2 2 2 $i
done;
tc 1

group GB 15
for i in {01..05}; do
tc GB-$i random_generator random 2 2 3 3 0
done;
for i in {06..10}; do
tc GB-$i random_generator random 2 2 3 3 1
done;

group GC 15
for i in {01..05}; do
tc GC-$i random_generator random 2 2 4 5 0
done;
for i in {06..10}; do
tc GC-$i random_generator random 2 2 4 5 1
done;

group GD 5
for i in {01..05}; do
tc GD-$i random_generator random 2 2 6 10 0
done;
for i in {06..10}; do
tc GD-$i random_generator random 2 2 6 9 1
done;
for i in {11..15}; do
tc GD-$i random_generator random 2 2 10 10 1
done;

group GE 15
for i in {01..05}; do
tc GE-$i random_generator random 3 3 3 3 0
done;
for i in {06..10}; do
tc GE-$i random_generator random 3 3 3 3 1
done;

group GF 15
for i in {01..05}; do
tc GF-$i random_generator random 3 4 3 4 0
done;
for i in {06..10}; do
tc GF-$i random_generator random 3 4 3 4 1
done;

group GG 15
for i in {01..05}; do
tc GG-$i random_generator random 4 5 4 5 0
done;
for i in {06..10}; do
tc GG-$i random_generator random 4 5 4 5 1
done;
for i in {11..15}; do
tc GG-$i random_generator random 5 5 5 5 1
done;

group GH 5
for i in {01..05}; do
tc GH-$i random_generator random 6 10 6 10 0
done;
for i in {06..10}; do
tc GH-$i random_generator random 6 10 6 10 1
done;
for i in {11..15}; do
tc GH-$i random_generator random 10 10 10 10 1
done;
