#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

setup_dirs
use_solution arnar.py

compile random_generator.py # Arguments: type of testcase

samplegroup
#sample sampleinputname
sample 01
sample 02

# group groupname score
group all 100
# tc testcasename random_generator arg1, arg2, ...
tc random-01 random_generator 1 5000 1 100 1 1
tc random-02 random_generator 1 5000 1 100 2 1 
tc random-03 random_generator 1 5000 1 100 3 1
tc random-04 random_generator 1 5000 1 100 4 1
tc random-05 random_generator 1 5000 1 100 5 1
tc random-06 random_generator 1 5000 1 100 6 1
tc random-07 random_generator 1 5000 1 100 7 1
tc random-08 random_generator 1 5000 1 100 8 1
tc random-09 random_generator 1 5000 1 100 9 1
tc random-10 random_generator 1 5000 1 100 10 1
tc random-11 random_generator 2 5000 1 100 11 1
tc random-12 random_generator 2 5000 1 100 12 1
tc random-13 random_generator 2 5000 1 100 13 1
tc random-14 random_generator 2 5000 1 100 14 1
tc random-15 random_generator 2 5000 1 100 15 1
tc random-16 random_generator 2 5000 1 100 16 1
tc random-17 random_generator 2 5000 1 100 17 1
tc random-18 random_generator 2 5000 1 100 18 1
tc random-19 random_generator 2 5000 1 100 19 1
tc random-20 random_generator 2 5000 1 100 20 1
tc random-21 random_generator 2 5000 1 100 21 1
tc random-22 random_generator 2 5000 1 100 22 1
tc random-23 random_generator 2 5000 1 100 23 1
tc random-24 random_generator 2 5000 1 100 24 1
tc random-25 random_generator 2 5000 1 100 25 1
tc random-26 random_generator 5000 5000 100 100 26 1

# Add more groups and adjust scoring if needed

generate_grader
cleanup_programs
