#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_100.py

compile random_generator.py

samplegroup
sample 1
sample 2

group GA 40
for i in {01..10}; do
tc GA-$i random_generator 2 200 random
done;
for i in {11..15}; do
tc GA-$i random_generator 200 200 random
done;

group GB 30
include_group GA
for i in {01..10}; do
tc GB-$i random_generator 200 5000 random
done;
for i in {11..15}; do
tc GB-$i random_generator 5000 5000 random
done;
tc GB-16 random_generator 5000 5000 start
tc GB-17 random_generator 5000 5000 end

group GC 30
include_group GB
for i in {01..05}; do
tc GC-$i random_generator 2000 200000 random
done;
for i in {06..10}; do
tc GC-$i random_generator 200000 200000 random
done;
tc GC-16 random_generator 200000 200000 start
tc GC-17 random_generator 200000 200000 end
