#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_hld_100.java

compile random_generator.py

samplegroup
sample 1

group GA-cycle 10
for i in {01..10}; do
    tc GA-cycle-$i random_generator cycle 3 20 1 20 0 100 yes
done

group GB-dfs 30
include_group GA-cycle
for i in {01..05}; do
    tc GB-dfs-$i random_generator complete 100 100 100 100 0 1000000000 yes
done

group GC-dijkstra 20
include_group GB-dfs
for i in {01..05}; do
    tc GC-dijkstra-$i random_generator complete 250 250 100000 100000 0 1000000000 yes
done

group GD-uf 30
include_group GC-dijkstra
for i in {01..05}; do
    tc GD-uf-$i random_generator general 10000 100000 100000 100000 0 1000000000 yes
done
tc GD-uf-06 random_generator general 100000 100000 100000 100000 0 1000000000 yes

group GE-hld 10
include_group GD-uf
for i in {01..05}; do
    tc GE-hld-$i random_generator general 10000 100000 100000 100000 0 1000000000 no
done
tc GE-hld-06 random_generator general 100000 100000 100000 100000 0 1000000000 no

