#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

setup_dirs
use_solution solution.py

compile random_generator.py
compile hard_generator.py
compile impossible_generator.py

# Arguments: mn_clauses mx_clauses mn_vsperclause mx_vsperclause mn_vars mx_vars

samplegroup
sample 01
sample 02

group A 50
tc A-01 random_generator 1 3 1 3 1 10
tc A-02 random_generator 1 3 1 3 1 10
tc A-03 random_generator 2 8 1 3 1 10
tc A-04 random_generator 2 8 1 3 1 10
tc A-05 random_generator 1 10 1 10 1 10
tc A-06 random_generator 1 10 1 10 1 10
tc A-07 random_generator 1 10 1 10 1 3
tc A-08 random_generator 1 10 1 10 1 2
tc A-09 random_generator 1 10 1 10 1 2
tc A-10 random_generator 1 10 1 10 1 1
tc A-11 random_generator 1 10 1 10 1 1
tc A-12 random_generator 1 10 1 10 1 1
tc A-13 random_generator 1 10 1 10 1 2
tc A-14 random_generator 1 10 1 10 1 2
tc A-15 hard_generator 5 10
tc A-16 hard_generator 10 5
tc A-17 hard_generator 10 10
tc A-18 hard_generator 10 10
tc A-19 impossible_generator 5 10
tc A-20 impossible_generator 10 5
tc A-21 impossible_generator 10 10
tc A-22 impossible_generator 10 10

group B 50
include_group A
tc B-01 random_generator 1 100 1 3 1 100
tc B-02 random_generator 1 100 1 3 1 100
tc B-03 random_generator 2 100 1 3 1 100
tc B-04 random_generator 2 100 1 3 1 100
tc B-05 random_generator 1 100 1 10 1 100
tc B-06 random_generator 1 100 1 10 1 100
tc B-07 random_generator 1 100 1 10 1 50
tc B-08 random_generator 1 100 1 10 1 50
tc B-09 random_generator 1 100 1 20 1 50
tc B-10 random_generator 1 100 1 20 1 50
tc B-11 random_generator 1 100 1 20 1 50
tc B-12 random_generator 1 100 1 20 1 50
tc B-13 random_generator 1 100 1 20 1 50
tc B-14 random_generator 1 100 1 20 1 50
tc B-15 hard_generator 50 100
tc B-16 hard_generator 100 50
tc B-17 hard_generator 100 100
tc B-18 hard_generator 100 100
tc B-19 impossible_generator 50 100
tc B-20 impossible_generator 100 50
tc B-21 impossible_generator 100 100
tc B-22 impossible_generator 100 100

generate_grader
cleanup_programs
