#!/usr/bin/python3
n = int(input())
names = [input() for _ in range(n)]
if n == 1:
    print(names[0])
elif n == 2:
    print(names[0])
    print(names[1])
elif n == 3:
    print(names[0])
    print(names[1])
    print(names[2])
elif n == 4:
    print(names[0])
    print(names[1])
    print(names[3])
    print(names[2])
elif n == 5:
    print(names[4])
    print(names[3])
    print(names[0])
    print(names[1])
    print(names[2])
elif n == 6:
    print(names[0])
    print(names[5])
    print(names[1])
    print(names[4])
    print(names[2])
    print(names[3])
elif n == 7:
    print(names[1])
    print(names[2])
    print(names[6])
    print(names[4])
    print(names[3])
    print(names[0])
    print(names[5])
elif n == 8:
    print(names[4])
    print(names[5])
    print(names[3])
    print(names[2])
    print(names[0])
    print(names[1])
    print(names[7])
    print(names[6])
elif n == 9:
    print(names[8])
    print(names[3])
    print(names[4])
    print(names[0])
    print(names[6])
    print(names[7])
    print(names[1])
    print(names[5])
    print(names[2])
elif n == 10:
    print(names[6])
    print(names[3])
    print(names[0])
    print(names[7])
    print(names[5])
    print(names[4])
    print(names[2])
    print(names[1])
    print(names[8])
    print(names[9])
elif n == 11:
    print(names[4])
    print(names[0])
    print(names[8])
    print(names[5])
    print(names[1])
    print(names[2])
    print(names[10])
    print(names[3])
    print(names[6])
    print(names[7])
    print(names[9])
