#!/bin/bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

setup_dirs
use_solution sol.cpp

compile random_generator.py

samplegroup
sample 01
sample 02
sample 03

group small 40
tc small-01 random_generator 1000
tc small-02 random_generator 1000
tc small-03 random_generator 1000
tc small-04 random_generator 1000
tc small-05 random_generator 1000
tc small-06 random_generator 1000
tc small-07 random_generator 1000
tc small-08 random_generator 1000
tc small-09 random_generator 1000
tc small-10 random_generator 1000
tc small-11 random_generator 1000
tc small-12 random_generator 1000

group large 60
include_group small
tc large-01 random_generator 100000
tc large-02 random_generator 100000
tc large-03 random_generator 100000
tc large-04 random_generator 100000
tc large-05 random_generator 100000
tc large-06 random_generator 100000
tc large-07 random_generator 100000
tc large-08 random_generator 100000
tc large-09 random_generator 100000
tc large-10 random_generator 100000
tc large-11 random_generator 100000
tc large-12 random_generator 100000

generate_grader
cleanup_programs

