#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

setup_dirs
use_solution hannes.py

compile random_generator.py # Arguments: minN maxN

samplegroup
#sample sampleinputname
sample 01
sample 02
sample 03

# group groupname score
group tiny 20
# tc testcasename random_generator arg1, arg2, ...

tc tiny-01 random_generator 9 9
tc tiny-02 random_generator 9 9
tc tiny-03 random_generator 9 9

group big 80
tc big-01 random_generator 3 299997 
tc big-02 random_generator 3 299997 
tc big-03 random_generator 3 299997 
tc big-04 random_generator 3 299997 
tc big-05 random_generator 3 299997 
tc big-06 random_generator 3 299997 
tc big-07 random_generator 3 299997 
tc big-08 random_generator 3 299997 
tc big-09 random_generator 3 299997 
tc big-10 random_generator 3 299997 
tc big-11 random_generator 3 299997 
tc big-12 random_generator 3 299997 
tc big-13 random_generator 3 299997 
tc big-14 random_generator 3 299997 
tc big-15 random_generator 300000 300000

# Add more groups and adjust scoring if needed

generate_grader
cleanup_programs
