#!/bin/bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

setup_dirs
use_solution sol.cpp

compile random_generator.py

samplegroup
sample 01
sample 02
sample 03

group ten 10
tc ten-01 random_generator 0 0
tc ten-02 random_generator 0 1
tc ten-03 random_generator 0 2
tc ten-04 random_generator 0 3
tc ten-05 random_generator 0 4
tc ten-06 random_generator 0 5

group fifty 30
include_group ten
tc fifty-01 random_generator 1 0
tc fifty-02 random_generator 1 1
tc fifty-03 random_generator 1 2
tc fifty-04 random_generator 1 3
tc fifty-05 random_generator 1 4
tc fifty-06 random_generator 1 5


group all 60
include_group ten
include_group fifty
tc all-01 random_generator 2 0
tc all-02 random_generator 2 1
tc all-03 random_generator 2 2
tc all-04 random_generator 2 3
tc all-05 random_generator 2 4
tc all-06 random_generator 2 5
tc all-07 random_generator 2 6
tc all-08 random_generator 2 7
tc all-09 random_generator 2 8
tc all-10 random_generator 2 9
tc all-11 random_generator 2 10
tc all-12 random_generator 2 11
tc all-13 random_generator 2 12
tc all-14 random_generator 2 13
tc all-15 random_generator 2 14
tc all-16 random_generator 2 15
tc all-17 random_generator 2 16

generate_grader
cleanup_programs

