#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution bjarki.cpp

compile random_generator.py # Arguments:

samplegroup
sample 1
sample 2

group GA 25
tc GA-1 random_generator 3
tc GA-2 random_generator 3
tc GA-3 random_generator 3
tc GA-4 random_generator 3
tc GA-5 random_generator 3
tc GA-6 random_generator 3

group GB 75
include_group GA
tc GB-1 random_generator 1
tc GB-2 random_generator 2
tc GB-3 random_generator 3
tc GB-4 random_generator 4
tc GB-5 random_generator 10
tc GB-6 random_generator 100
tc GB-7 random_generator 500
tc GB-8 random_generator 813
tc GB-9 random_generator 1000
