#!/usr/bin/env bash
export PPATH
PPATH=$(realpath ..)
# shellcheck source-path=SCRIPTDIR
. ../../../testdata_tools/gen.sh

use_solution runar_100.py

compile only_queries_generator.py
compile random_generator.py

samplegroup
limits max_n=100
sample 1
sample 2

group GA 20
limits max_n=20
for i in {01..10}; do
    tc "GA-$i" random_generator 20 0 0
    desc "Random case with only queries and small n."
done;

group GB 50
include_group GA
limits max_n=1000
tc 1
tc 2
for i in {1..3}; do
    tc "GB-$i-1" random_generator 1000 93 2
    desc "Random case with small n and mostly additions."
    tc "GB-$i-2" random_generator 1000 50 2
    desc "Random case with small n and mostly additions/queries."
    tc "GB-$i-3" random_generator 1000 57 37
    desc "Random case with small n and mostly additions/removals."
    tc "GB-$i-4" random_generator 1000 40 40
    desc "Random case with small n and a mix of all queries."
done;
tc GB-5 random_generator 1000 addrem
desc "Edge case with lots of additions, then lots of removals (small n)."
tc GB-6 random_generator 1000 addq
desc "Edge case with lots of additions, then lots of queries (small n)."

group GC 30
include_group GA
include_group GB
limits max_n=200000
tc GC-1 random_generator 200000 93 2
desc "Random case with big n and mostly additions."
tc GC-2 random_generator 200000 50 2
desc "Random case with big n and mostly additions/queries."
tc GC-3 random_generator 200000 57 37
desc "Random case with big n and mostly additions/removals."
tc GC-4 random_generator 200000 40 40
desc "Random case with big n and a mix of all queries."
tc GC-5 random_generator 200000 addrem
desc "Edge case with lots of additions, then lots of removals (big n)."
tc GC-6 random_generator 200000 addq
desc "Edge case with lots of additions, then lots of queries (big n)."
