#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_100.py

compile random_generator.py # Arguments:

samplegroup
sample 1

group GA 100
tc GA-test random_generator
