#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution atli_100.py opt

compile random_generator.py

samplegroup
limits max_n=10**100
sample 1
sample 2
sample 3

group GA 24
limits max_n=3
for i in {1..3}; do
tc GA-$i random_generator $i $i
done;

group GB 24
include_group GA
limits max_n=30
tc 1
for i in 4 5 {7..30}; do
tc GB-$i random_generator $i $i
done;

group GC 24
include_group GB
limits max_n=30000
tc 2
for i in {01..20}; do
tc GC-$i random_generator 31 30000
done;

group GD 24
include_group GC
limits max_n=10**12
for i in {01..20}; do
tc GD-$i random_generator 30001 10**12
done;

group GE 4
include_group GD
limits max_n=10**100
tc 3
for i in {01..20}; do
tc GE-$i random_generator 10**12+1 10**100
done;
