#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution bjarki_100.cpp

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 33
for i in {01..10}; do
tc GA-$i random_generator 2 10
done;

group GB 27
include_group GA
for i in {01..10}; do
tc GB-$i random_generator 26 10
done;

group GC 40
include_group GB
for i in {01..10}; do
tc GC-$i random_generator 26 1000
done;

