#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

setup_dirs
use_solution bjarki-3.cpp

compile random_generator.py # Arguments: N M seed

samplegroup
sample 01

# 1: N <= 1000, M <= 10^4
group small 30
tc small-01 random_generator random 1000 100
tc small-02 random_generator random 1000 1000
tc small-03 random_generator random 1000 10000
tc small-05 random_generator random 1000 10000

# 1: N <= 10^6, M <= 10^5
group medium 30
include_group small
tc medium-01 random_generator random 1000000 10000
tc medium-02 random_generator random 1000000 10000
tc medium-03 random_generator random 1000000 100000
tc medium-04 random_generator random 1000000 100000
tc medium-05 random_generator notrandom 1000000 100000
tc medium-06 random_generator notrandom 1000000 100000

# 2:  N <= 10^12, M <= 10^5
group big 40
include_group medium
tc big-01 random_generator random 1000000000000 1000
tc big-02 random_generator random 1000000000000 10000
tc big-03 random_generator random 1000000000000 100000
tc big-04 random_generator random 1000000000000 100000
tc big-05 random_generator random 1000000000000 100000

generate_grader
cleanup_programs

