#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution samuel_100.py

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3
sample 4

group GA 100
tc 1
tc 2
tc 3
tc 4
