#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution bjarki_100.cpp opt

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 50
for i in {01..25}; do
tc GA-$i random_generator easy
done;

group GB 50
include_group GA
for i in {01..25}; do
tc GB-$i random_generator hard
done;

