#!/usr/bin/env bash
export PPATH
PPATH=$(realpath ..)
# shellcheck source-path=SCRIPTDIR
. ../../../testdata_tools/gen.sh

use_solution atli.py opt

compile random_generator.py

samplegroup
limits max_h=20 max_w=20 max_d=20 min_h=1 min_w=1 min_d=1
sample 1
sample 2
sample 3
sample 4

group GA 20
tc 1
limits max_h=3 max_w=3 max_d=3 min_h=1 min_w=1 min_d=1
for i in {1..3}; do
    for j in {1..3}; do
        for k in {1..3}; do
            [ "$i" -eq 3 ] && [ "$j" -eq 3 ] && [ "$k" -eq 3 ] && continue;
            tc "GA-$i-$j-$k" random_generator "$i" "$j" "$k" "A"
            desc "Random small input with side lengths 1-3."
        done;
    done;
done;

group GB 30
tc 2
limits max_h=8 max_w=8 max_d=8 min_h=2 min_w=2 min_d=2
for i in 2 4 8; do
    for j in 2 4 8; do
        for k in 2 4 8; do
            [ "$i" -eq 2 ] && [ "$j" -eq 2 ] && [ "$k" -eq 2 ] && continue;
            tc "GB-$i-$j-$k" random_generator "$i" "$j" "$k" "B"
            desc "Random small input with side lengths 2-8."
        done;
    done;
done;

group GC 20
limits max_h=100 max_w=100 max_d=1 min_h=1 min_w=1 min_d=1
for i in 1 2 3 100; do
    for j in 1 2 3 100; do
        [ "$i" -le 3 ] && [ "$j" -le 3 ] && continue;
        tc "GC-$i-$j" random_generator "$i" "$j" 1 "C"
        desc "Random input with side lengths 1-100, but depth is 1."
    done;
done;

group GD 30
limits max_h=100 max_w=100 max_d=100 min_h=1 min_w=1 min_d=1
include_group GA
include_group GB
include_group GC
tc 3
tc 4
for i in 1 2 5 100; do
    for j in 1 2 5 100; do
        for k in 2 5 100; do
            [ "$i" -le 2 ] && [ "$j" -le 2 ] && [ "$k" -le 2 ] && continue;
            [ "$i" -ne 1 ] && [ "$j" -ne 1 ] && [ "$i" -le 10 ] && [ "$j" -le 10 ] && [ "$k" -le 10 ] && continue;
            tc "GD-$i-$j-$k" random_generator "$i" "$j" "$k" "D"
            desc "Random input with side lengths 1-100."
        done;
    done;
done;
