#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution sammi_100.cpp opt

compile random_generator.py

samplegroup
sample 1
sample 2
sample 3

group GA 100
tc 3
for i in {01..16}; do
if [ $i = 12 ]; then continue; fi
tc GA-draw-$i random_generator draws.txt ${i#0}
done;
for i in {01..42}; do
tc GA-x-$i random_generator xwins.txt ${i#0}
done;
for i in {01..42}; do
tc GA-o-$i random_generator owins.txt ${i#0}
done;

