#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution hannes_100.py

compile random_generator.py

samplegroup
sample 1
sample 2

group GA 50
tc 1
tc 2
for i in {01..40}; do
tc small-$i random_generator 1 1000
done;

group GB 50
include_group GA
for i in {01..10}; do
tc big-$i random_generator 1 100000
done;